apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  serviceName: mongodb
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:4.4
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: app-config
